import Foundation

enum QuestionsBank {
    static let questions: [String] = [
        "What's one thing I do that always makes you smile?",
        "If we could teleport anywhere right now, where would you want to go?",
        "What's your favorite memory of us together?",
        "What song reminds you of us?",
        "What's something new you'd like us to try together?",
        "What was your first impression of me?",
        "What's the most romantic thing I've ever done for you?",
        "If we had a whole weekend with no plans, what would you want to do?",
        "What's one thing about me that you find surprising?",
        "What does your perfect date night look like?",
        "What's a small thing I do that means a lot to you?",
        "If you could relive one day we've spent together, which would it be?",
        "What's something you've always wanted to tell me but haven't?",
        "What's your love language, and do you feel I speak it well?",
        "What's a dream you have for our future together?",
        "What habit of mine do you find most endearing?",
        "If we wrote a book about our love story, what would the title be?",
        "What's the funniest thing that's happened to us?",
        "What's one thing you admire most about me?",
        "How do you feel most loved by me?",
        "What's a fear you have that you trust me with?",
        "What's the best advice you'd give to a new couple?",
        "What's one thing we should do more often?",
        "What's your favorite thing about our relationship?",
        "If you could change one thing about how we met, what would it be?",
        "What's a goal you'd like us to achieve together this year?",
        "What's the most thoughtful gift you've ever received from me?",
        "What do you think makes our relationship unique?",
        "What's something you're grateful for about us?",
        "What's your favorite way to spend a lazy Sunday together?",
        "What's a compliment you never get tired of hearing?",
        "What's one thing that always cheers you up when you're sad?",
        "What does home feel like to you?",
        "What's a tradition you'd like us to start?",
        "What's the bravest thing you've ever done for love?",
        "If you could describe our relationship in three words, what would they be?",
        "What's a movie that reminds you of us?",
        "What's the best meal we've ever shared?",
        "What's something you want to learn together?",
        "What makes you feel safe in our relationship?",
        "What's a place that's special to us?",
        "What's the hardest thing we've overcome together?",
        "What's one thing you wish you knew about me sooner?",
        "What does a perfect morning together look like?",
        "What's a bucket list item you want us to check off?",
        "What quality of mine are you most proud of?",
        "What's the sweetest text I've ever sent you?",
        "What's your favorite inside joke we have?",
        "What makes you fall in love with me all over again?",
        "What's a lesson our relationship has taught you?",
        "What's something you'd love to surprise me with?",
        "What's the most spontaneous thing we've done?",
        "What do you look forward to most about growing old together?",
        "What's your favorite photo of us?",
        "What's something I do that makes you feel special?",
        "If we could have dinner with any couple, fictional or real, who?",
        "What's the best trip we've taken together?",
        "What's a show we should binge-watch together?",
        "What scent reminds you of me?",
        "What's one thing about our relationship you'd never change?",
        "What's your favorite season to experience together?",
        "What does trust mean to you in our relationship?",
        "What's the most important thing in a relationship?",
        "What's a skill you think we complement each other in?",
        "What's your favorite way I show affection?",
        "What's a challenge you want us to take on together?",
        "What would you write in a love letter to me?",
        "What does partnership mean to you?",
        "What's the best decision we've made together?",
        "What's something small that brightens your day?",
        "What's a hobby you'd like us to pick up together?",
        "What's the most important conversation we've had?",
        "What does forgiveness look like in our relationship?",
        "What's a food that reminds you of a special moment we shared?",
        "What's the kindest thing a stranger has done for us?",
        "What's your favorite thing about waking up next to me?",
        "What's a silly thing that makes you love me more?",
        "What's the most beautiful place we've visited together?",
        "What's a value we both share?",
        "What's the most meaningful gift you could receive?",
        "What does a perfect evening together look like?",
        "What's something you never want to take for granted about us?",
        "What's a song you'd dedicate to me?",
        "What's the best surprise I've ever given you?",
        "What makes our relationship feel like home?",
        "What's one thing you always want to remember about us?",
        "What's the most fun date we've ever been on?",
        "What's a quality you want to develop together?",
        "What does vulnerability mean to you?",
        "What's a cause or passion we both care about?",
        "What's the best part of being in a committed relationship?",
        "What's something you want more of in our relationship?",
        "What does unconditional love mean to you?",
        "What's a ritual that strengthens our bond?",
        "What's the most unexpected thing about loving me?",
        "What's a dream vacation you want us to take?",
        "What's something you've learned about yourself through our relationship?",
        "What would you tell your younger self about love?",
        "What's the coziest moment we've shared?",
        "What are you most excited about for our next chapter?",
        "What's one thing you want me to know today?",
        "What's a comfort food that reminds you of us?",
        "What does loyalty mean to you?",
        "What's the most romantic place you can imagine?",
        "What's a talent of mine that you admire?",
        "What does balance look like in our relationship?",
        "What's a childhood memory that shaped how you love?",
        "What's the most important promise we've made to each other?",
        "What does respect look like in our relationship?",
        "What's a date idea you've been wanting to try?",
        "What's the best thing about being on the same team?",
        "What's something you're looking forward to this month?",
        "What makes you proud to be my partner?",
        "What's a moment where you felt deeply connected to me?",
        "What's the best way to resolve a disagreement?",
        "What's a quality in me that inspires you?",
        "What's the most peaceful moment we've shared?",
        "What's a shared interest that brought us closer?",
        "What does commitment mean to you?",
        "What's a way we can keep the spark alive?",
        "What's the most meaningful date we've been on?",
        "What's one thing you hope never changes about us?",
        "What's the best compliment you've received from me?",
        "What does happiness in a relationship look like?",
        "What's something new about me you've noticed recently?",
        "What's a place you'd love for us to live someday?",
        "What's the best part of our daily routine together?",
        "What's a movie we should watch on our next date night?",
        "What's the most selfless thing you've done for our relationship?",
        "What's something that makes our relationship stronger?",
        "What's a way I've helped you grow?",
        "What does empathy look like between us?",
        "What's the most heartfelt apology you've received?",
        "What's a tradition from your family you want to bring into ours?",
        "What's a way we celebrate each other?",
        "What's one word that describes how I make you feel?",
        "What's the most adventurous thing you'd try with me?",
        "What's a quote that reminds you of our love?",
        "What does patience look like in our relationship?",
        "What's the most comforting thing I do for you?",
        "What's a way we've grown together this year?",
        "What's the best holiday memory we share?",
        "What's your love story highlight reel?",
        "What makes you excited to come home to me?",
        "What's a new restaurant you want to try together?",
        "What does intimacy mean to you beyond the physical?",
        "What's a way we support each other's dreams?",
        "What's the most important lesson love has taught you?",
        "What's a shared goal that motivates you?",
        "What's a way we can be more intentional about our time?",
        "What's the best road trip we've taken?",
        "What's something you want to create together?",
        "What does acceptance look like in our relationship?",
        "What's the most memorable sunrise or sunset we've shared?",
        "What's something about our future that excites you?",
        "What's a way to make ordinary moments extraordinary?",
        "What's a simple pleasure we both enjoy?",
        "What's the best thing about our communication?",
        "What's something you treasure about our story?",
        "What's a life lesson you've learned from me?",
        "What does being present together mean to you?",
        "What's the most joyful moment we've shared recently?",
        "What's a way we keep each other grounded?",
        "What's something you always look forward to with me?",
        "What does growing old together look like in your mind?",
        "What's a way we can better show appreciation?",
        "What's the sweetest thing you've witnessed me do?",
        "What's a way our love has evolved over time?",
        "What's a favorite cozy activity we do together?",
        "What's something that still gives you butterflies about me?",
        "What's the most important ingredient in our recipe for love?",
        "What's your favorite 'us' time of day?",
        "What's a way we turn challenges into opportunities?",
        "What's the best decision you've made in our relationship?",
        "What does showing up for each other mean to you?",
        "What's a wish you have for us?",
        "What's one thing about today you're grateful for?",
        "What's the most beautiful thing about our love?",
        "What's a way we can laugh more together?",
        "What does being truly known by someone feel like?",
        "What's a favorite rainy day memory together?",
        "What's something we should celebrate more?",
        "What's your definition of a soulmate?",
        "What's the most important 'little thing' in a relationship?",
        "What's a way we inspire each other?",
        "What makes our partnership feel balanced?",
        "What's a way we've surprised each other?",
        "What's the kindest thing you've done for me that I might not know about?",
        "What's a way our differences make us stronger?",
        "What's a shared secret that bonds us?",
        "What's the most authentic version of us?",
        "What's your favorite chapter in our love story so far?",
        "What's a way we protect our relationship?",
        "What's the most meaningful silence we've shared?",
        "What's something you'd love to hear me say more often?",
        "What does forever mean to you?",
        "What's the most important thing I can do for you today?",
        "What's a way we keep things interesting?",
        "What's a quality of ours that others admire?",
        "What's the best hug you've gotten from me?",
        "What's something we'll laugh about in 20 years?",
        "What's the most romantic gesture you can imagine?",
        "What's a way we choose each other every day?",
        "What's your favorite thing we've built together?",
        "What's a way love has made you braver?",
        "What's the most important boundary in our relationship?",
        "What does a perfect anniversary celebration look like?",
        "What's a way we make each other better people?",
        "What's the most tender moment we've shared?",
        "What's a way we keep our friendship alive within our romance?",
        "What does devotion look like to you?",
        "What's a shared dream that keeps you going?",
        "What's the best cup of coffee or tea we've shared?",
        "What's something you admire about how we handle conflict?",
        "What's a way we honor each other's individuality?",
        "What does a love-filled home look like?",
        "What's the most spontaneous romantic thing you'd do?",
        "What's a way we can deepen our connection this week?",
        "What's the most powerful three words beyond 'I love you'?",
        "What's a way our love makes the world a better place?",
        "What's something you want our love story to always include?",
        "What's the most healing thing about our relationship?",
        "What's a way we celebrate the mundane?",
        "What's the best unexpected moment in our relationship?",
        "What does wholehearted love mean to you?",
        "What's a way we nourish our relationship?",
        "What's the most important thing you want me to remember?",
        "What's a way love has surprised you?",
        "What's the sweetest good morning you've received from me?",
        "What does being cherished feel like?",
        "What's a new adventure you'd like us to plan?",
        "What's the most meaningful anniversary we've celebrated?",
        "What's a way we practice gratitude together?",
        "What's something about our love that feels like magic?",
        "What's the best thing about the way we argue?",
        "What's a favorite holiday tradition we share?",
        "What does a perfect 'just because' surprise look like?",
        "What's a way our relationship heals old wounds?",
        "What's the most courageous conversation we've had?",
        "What's a way we've redefined love together?",
        "What's the most generous thing about our relationship?",
        "What's a shared victory that made us proud?",
        "What's a way we stay curious about each other?",
        "What's the most playful thing about our relationship?",
        "What does emotional safety mean to you?",
        "What's a way we keep growing individually within our partnership?",
        "What's the warmest feeling our love gives you?",
        "What's something you want to always protect about us?",
        "What's the most creative thing we've done together?",
        "What's a way we navigate uncertainty together?",
        "What's the most honest conversation we've had?",
        "What does compassion look like in our daily life?",
        "What's a way we make time stand still?",
        "What's the most life-changing moment in our relationship?",
        "What's a way we keep romance alive in the everyday?",
        "What's something about our love that gives you hope?",
        "What's the most nurturing thing about being with me?",
        "What's a way we bridge our differences?",
        "What's the most fun we've had doing absolutely nothing?",
        "What's a way our love story is still being written?",
        "What's the most grounding thing about our relationship?",
        "What's something about us that makes you deeply happy?",
        "What's a way we light up each other's lives?",
        "What's the most profound thing love has shown you?",
        "What's one more thing you want to share with me tonight?"
    ]

    static func questionForDate(_ date: Date) -> String {
        let dayOfYear = Calendar.current.ordinality(of: .day, in: .year, for: date) ?? 1
        let index = (dayOfYear - 1) % questions.count
        return questions[index]
    }

    static func indexForDate(_ date: Date) -> Int {
        let dayOfYear = Calendar.current.ordinality(of: .day, in: .year, for: date) ?? 1
        return (dayOfYear - 1) % questions.count
    }
}
